version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Dockerfile を指定
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - db
    command: >
      sh -c "composer install && php artisan serve --host=0.0.0.0 --port=80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  frontend:
    image: node:18
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
